//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tercuman.Website.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resource
    {
        public int ResourceID { get; set; }
        public string ContainerName { get; set; }
        public string ResourceName { get; set; }
        public string LangCode { get; set; }
        public string Value { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string LanguageCode { get; set; }
        public string ResourceType { get; set; }
    }
}
